version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: frontend
    environment:
      TZ: Asia/Tokyo
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    working_dir: /app
    command: yarn dev
    networks:
      - default
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: db
    env_file: .env.mysql
    environment:
      TZ: Asia/Tokyo
    ports:
      - '3306:3306'
    command: >
      mysqld
        --character-set-server=utf8
        --collation-server=utf8_unicode_ci
        --skip-character-set-client-handshake
    volumes:
      - ./database/dbdata:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - default

networks:
  default:
volumes:
  dbdata:
